language: php
sudo: required
dist: trusty
group: edge

branches:
  only:
    - 0.x
    - Latest-testing
    - dev

notifications:
  irc:
    channels:
      - "irc.synirc.net#TmuxAnnounce"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
      - "\x030[\x0310Travis-ci\x030]\x03 Commit \x0314{%{commit}}\x03 by \x0315(%{author})\x03@\x0313%{repository_name}/%{branch}\x03 has \x037%{result}\x03: \x032%{build_url}\x03"

php:
  - '7.1'

addons:
  mariadb: '10.1'
  apt:
      packages:
      - curl

before_install:
    - composer validate

install:
    - yes '' | pecl install imagick
    # Install composer packages.
    - composer install --prefer-dist

before_script:
     # Create mysql user.
     - mysql -u root -e "GRANT ALL ON TEST.* TO 'NNTMUX'@'localhost' IDENTIFIED BY 'NNTMUX';"
     - mysql -u root -e "GRANT FILE ON *.* TO 'NNTMUX'@'localhost';"
     # Disable apparmor.
     - if service apparmor status; then service apparmor stop; update-rc.d -f apparmor remove; service apparmor teardown; fi
     # Change MySQL settings.
     - if [[ -f /etc/mysql/my.cnf ]]; then sudo sed -i "s/\[mysqld\]/\[mysqld\]\ngroup_concat_max_len = 8192/" /etc/mysql/my.cnf; fi
     # Change PHP settings.
     - echo 'max_execution_time = 120' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
     - echo 'memory_limit = 1024M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
     # Required for PHP 7
     - if [[ -f ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
      - sudo a2enmod rewrite actions fastcgi alias
      - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
     # Set permissions, can't use newgrp with travis so we need to do it this way.
     - sudo chmod -R 777 /home/travis/
     # Configure mysql environment settings
     - cp .env.example .env
     - sed -i 's/DB_USER\ \=/DB_USER\ \=\ NNTMUX/g' .env
     - sed -i 's/DB_PASSWORD\ \=/DB_PASSWORD\ \=\ NNTMUX/g' .env
     - sed -i 's/DB_NAME\ \=/DB_NAME\ \=\ TEST/g' .env
     - sed -i 's/ADMIN_USER\ \=/ADMIN_USER\ \=\ NNTMUX/g' .env
     - sed -i 's/ADMIN_PASS\ \=/ADMIN_PASS\ \=\ NNTMUX/g' .env
     - sed -i 's/ADMIN_EMAIL\ \=/ADMIN_EMAIL\ \=\ example@example.com/g' .env

script:
   phpunit
